# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for distributing app using Firebase App Distributions"
      lane :distribute_android do
          gradle(
            task:"assemble",
            build_type:"Debug"
          )
          firebase_app_distribution(
              service_credentials_file: "tools/firebase/aldera-multitasker-b969abb9fda0.json",
              app: "1:1001791539654:android:dc81a2b1f8323d88ffcac7",
              groups_file: "tools/firebase/groups.txt",
          )
      end
end
